services:
  - type: web
    name: be_sotta
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://be-sotta.onrender.com

      # Database PostgreSQL dari Neon.tech (sesuaikan dengan connection string kamu)
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-dark-cell-a8spepkp-pooler.eastus2.azure.neon.tech
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_CF8H0DIGXlJw
